### ISSUE TITLE
Typescript error in withResizeDetector.d.ts

### ISSUE THREAD

**Issue by hogan** [maslianok/react-resize-detector#153]
I am getting this error:
`node_modules/react-resize-detector/build/withResizeDetector.d.ts(1,8): error TS1259: Module '"node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag`

If I change `import React, { ComponentType } from 'react';`
to `import * as React from 'react';
import { ComponentType } from 'react';`
it works. But it is inconvenient to have to manually edit the file in node_modules.

My TS version is 3.7.5.

**Comment by maslianok** [comment]
Oh, that's strange...

I can't reproduce this bug. Can you provide a codesnippet so we can reproduce the error?

Is it possible that you have some specific TS config that leads to this error?

**Comment by maslianok** [comment]
Thanks for the details. I’ll check it out and get back to you

**Comment by maslianok** [comment]
Fixed in v6.7.2

Thanks for filing the issue 👍

**Comment by vilmosioo** [comment]
Hi! It seems this issue came back with 8.0.4 here:

https://github.com/maslianok/react-resize-detector/commit/68eae2f2eb4e97d17f0443080f905c942de105bb
