### ISSUE TITLE
serverside ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by barbalex** [maslianok/react-resize-detector#93]
I am using gatsby and getting this error when building:
```
alexa@PCA C:\Users\alexa\vermehrung
$ yarn build
yarn run v1.22.4
$ gatsby clean && gatsby build
info Deleting .cache, public
info Successfully deleted directories
success open and validate gatsby-configs - 0.039s
success load plugins - 1.650s
success onPreInit - 0.014s
success delete html and css files from previous builds - 0.009s
success initialize cache - 0.008s
success copy gatsby files - 0.070s
success onPreBootstrap - 0.006s
success createSchemaCustomization - 0.037s
success source and transform nodes - 0.172s
success building schema - 0.257s
success createPages - 0.044s
success createPagesStatefully - 0.066s
success onPreExtractQueries - 0.001s
success update schema - 0.021s
success extract queries from components - 1.525s
success write out requires - 0.007s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.079s
success onPostBootstrap - 0.085s
⠀
info bootstrap finished - 6.826 s
⠀
success Building production JavaScript and CSS bundles - 115.974s
success Rewriting compilation hashes - 0.005s
success run queries - 117.231s - 35/35 0.30/s
failed Building static HTML for pages - 51.774s

 ERROR #95313

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html



  ReferenceError: Element is not defined

  - render-page.js:183275 Module../node_modules/react-resize-detector/lib/esm/components/ResizeDetector.js
    C:/Users/alexa/vermehrung/public/render-page.js:183275:76

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:183428 Module../node_modules/react-resize-detector/lib/esm/index.js
    C:/Users/alexa/vermehrung/public/render-page.js:183428:84

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:249242 Module../src/components/Header/Doku.js
    C:/Users/alexa/vermehrung/public/render-page.js:249242:79

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:249402 Module../src/components/Header/index.js
    C:/Users/alexa/vermehrung/public/render-page.js:249402:63

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:249423 Module../src/components/Layout.js
    C:/Users/alexa/vermehrung/public/render-page.js:249423:65

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:292429 Module../src/pages/404.js
    C:/Users/alexa/vermehrung/public/render-page.js:292429:76

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:694 Object../.cache/sync-requires.js
    C:/Users/alexa/vermehrung/public/render-page.js:694:323

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:644 Module../.cache/static-entry.js
    C:/Users/alexa/vermehrung/public/render-page.js:644:1763

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30


not finished Generating image thumbnails - 170.852s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This did not happen before updating from v4 to v5.

Seems related to https://github.com/maslianok/react-resize-detector/issues/70

**Comment by devuxer** [comment]
I get something pretty similar:

```
failed Building static HTML for pages - 15.752s

 ERROR #95313 

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html


  290 |   // eslint-disable-line react/forbid-prop-types
  291 |   targetRef: oneOfType([func, shape({
> 292 |     current: instanceOf(Element)
      |                        ^
  293 |   })]),
  294 |   onResize: func,
  295 |   render: func,


  WebpackError: ReferenceError: Element is not defined

  - ResizeDetector.js:292 Module../node_modules/react-resize-detector/lib/esm/components/ResizeDetector.js
    node_modules/react-resize-detector/lib/esm/components/ResizeDetector.js:292:24

  - index.js:1 Module../node_modules/react-resize-detector/lib/esm/index.js
    node_modules/react-resize-detector/lib/esm/index.js:1:1
```

Only happens when I do Gatsby `build`, not `develop`.

**Comment by maslianok** [comment]
Please try v5.0.4. It should be fixed.

**Comment by barbalex** [comment]
@maslianok thanks for you quick responce!

I updated to v5.0.4

then ran (three times):
```
del yarn.lock && rmdir /s node_modules && yarn && yarn build
```
where `yarn build` also cleans the gatsby cache

Unfortunately the problem remains:

```
alexa@PCA C:\Users\alexa\vermehrung
$ yarn build
yarn run v1.22.4
$ gatsby clean && gatsby build
info Deleting .cache, public
info Successfully deleted directories
success open and validate gatsby-configs - 0.031s
success load plugins - 0.949s
success onPreInit - 0.012s
success delete html and css files from previous builds - 0.009s
success initialize cache - 0.008s
success copy gatsby files - 0.059s
success onPreBootstrap - 0.006s
success createSchemaCustomization - 0.026s
success source and transform nodes - 0.149s
success building schema - 0.247s
success createPages - 0.044s
success createPagesStatefully - 0.064s
success onPreExtractQueries - 0.001s
success update schema - 0.020s
success extract queries from components - 1.054s
success write out requires - 0.005s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.067s
success onPostBootstrap - 0.074s
⠀
info bootstrap finished - 5.023 s
⠀
success Building production JavaScript and CSS bundles - 83.375s
success Rewriting compilation hashes - 0.004s
success run queries - 84.611s - 35/35 0.41/s
failed Building static HTML for pages - 51.805s

 ERROR #95313

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html



  ReferenceError: Element is not defined

  - render-page.js:183264 Module../node_modules/react-resize-detector/lib/esm/components/ResizeDetector.js
    C:/Users/alexa/vermehrung/public/render-page.js:183264:11

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:183434 Module../node_modules/react-resize-detector/lib/esm/index.js
    C:/Users/alexa/vermehrung/public/render-page.js:183434:84

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:249248 Module../src/components/Header/Doku.js
    C:/Users/alexa/vermehrung/public/render-page.js:249248:79

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:249408 Module../src/components/Header/index.js
    C:/Users/alexa/vermehrung/public/render-page.js:249408:63

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:249429 Module../src/components/Layout.js
    C:/Users/alexa/vermehrung/public/render-page.js:249429:65

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:292439 Module../src/pages/404.js
    C:/Users/alexa/vermehrung/public/render-page.js:292439:76

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:694 Object../.cache/sync-requires.js
    C:/Users/alexa/vermehrung/public/render-page.js:694:323

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:644 Module../.cache/static-entry.js
    C:/Users/alexa/vermehrung/public/render-page.js:644:1763

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30


not finished Generating image thumbnails - 138.274s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by maslianok** [comment]
Ok, if we can't polyfill Element - let's remove it :) PropTypes should help with validation, not break builds ))

Please, try v5.0.5

**Comment by barbalex** [comment]
Still getting it:
```
yarn run v1.22.4
$ gatsby clean && gatsby build
info Deleting .cache, public
info Successfully deleted directories
success open and validate gatsby-configs - 0.031s
success load plugins - 0.991s
success onPreInit - 0.010s
success delete html and css files from previous builds - 0.009s
success initialize cache - 0.006s
success copy gatsby files - 0.054s
success onPreBootstrap - 0.006s
success createSchemaCustomization - 0.026s
success source and transform nodes - 0.150s
success building schema - 0.254s
success createPages - 0.041s
success createPagesStatefully - 0.064s
success onPreExtractQueries - 0.001s
success update schema - 0.025s
success extract queries from components - 1.035s
success write out requires - 0.006s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.066s
success onPostBootstrap - 0.072s
⠀
info bootstrap finished - 5.063 s
⠀
success Building production JavaScript and CSS bundles - 114.728s
success Rewriting compilation hashes - 0.005s
success run queries - 116.153s - 35/35 0.30/s
failed Building static HTML for pages - 51.750s

 ERROR #95313

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html



  ReferenceError: Element is not defined

  - render-page.js:183406 withResizeDetector
    C:/Users/alexa/vermehrung/public/render-page.js:183406:78

  - render-page.js:249249 Module../src/components/Header/Doku.js
    C:/Users/alexa/vermehrung/public/render-page.js:249249:3964

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:249402 Module../src/components/Header/index.js
    C:/Users/alexa/vermehrung/public/render-page.js:249402:63

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:249423 Module../src/components/Layout.js
    C:/Users/alexa/vermehrung/public/render-page.js:249423:65

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:292433 Module../src/pages/404.js
    C:/Users/alexa/vermehrung/public/render-page.js:292433:76

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:694 Object../.cache/sync-requires.js
    C:/Users/alexa/vermehrung/public/render-page.js:694:323

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:644 Module../.cache/static-entry.js
    C:/Users/alexa/vermehrung/public/render-page.js:644:1763

  - render-page.js:30 __webpack_require__
    C:/Users/alexa/vermehrung/public/render-page.js:30:30

  - render-page.js:94
    C:/Users/alexa/vermehrung/public/render-page.js:94:18

  - render-page.js:97
    C:/Users/alexa/vermehrung/public/render-page.js:97:10

  - render-page.js:3 webpackUniversalModuleDefinition
    C:/Users/alexa/vermehrung/public/render-page.js:3:20


not finished Generating image thumbnails - 169.549s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by DovahBrownies** [comment]
+1 on this issue. Happening on NextJS (server-side as well).

Perhaps `instanceOf(Element)` could be the culprit here?
https://github.com/maslianok/react-resize-detector/blob/ddc282dd2a3215655ee9faca081b3fd183eb00e8/src/hoc/withResizeDetector.js#L30

**Comment by maslianok** [comment]
Yeah, I removed it from the main component but forgot about HOC.

Can you please try v5.0.6?

**Comment by barbalex** [comment]
v5.0.6 works for me.

If this were a paid product I would now thank you for the great service.

As it is open source and I have no right to expect anything from you, I hove you will enjoy a fine beer this evening.

**Comment by maslianok** [comment]
@barbalex haha, thanks man 🤝

**Comment by DovahBrownies** [comment]
@maslianok Awesome work. Hope my comment was helpful haha.

**Comment by devuxer** [comment]
Gatsby build works for v5.0.6 for me as well.
